/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const EvaluationResult = IDL.Record({
  'weaknesses' : IDL.Text,
  'strengths' : IDL.Text,
  'confidenceRating' : IDL.Nat,
  'communicationRating' : IDL.Nat,
  'score' : IDL.Nat,
  'recommendation' : IDL.Text,
  'technicalRating' : IDL.Nat,
});
export const Timestamp = IDL.Int;
export const Candidate = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'weaknesses' : IDL.Opt(IDL.Text),
  'strengths' : IDL.Opt(IDL.Text),
  'passcode' : IDL.Text,
  'name' : IDL.Text,
  'designation' : IDL.Text,
  'createdAt' : Timestamp,
  'audioLink' : IDL.Opt(IDL.Text),
  'email' : IDL.Text,
  'score' : IDL.Opt(IDL.Nat),
  'interviewDate' : IDL.Opt(Timestamp),
  'department' : IDL.Text,
});
export const InterviewSession = IDL.Record({
  'status' : IDL.Text,
  'completedAt' : IDL.Opt(Timestamp),
  'startedAt' : Timestamp,
  'candidateEmail' : IDL.Text,
  'questions' : IDL.Vec(IDL.Text),
  'sessionId' : IDL.Text,
  'currentQuestionIndex' : IDL.Nat,
  'tabSwitchCount' : IDL.Nat,
});
export const DepartmentStat = IDL.Record({
  'avgScore' : IDL.Nat,
  'count' : IDL.Nat,
  'department' : IDL.Text,
});
export const Stats = IDL.Record({
  'avgScore' : IDL.Nat,
  'total' : IDL.Nat,
  'pending' : IDL.Nat,
  'completed' : IDL.Nat,
  'inProgress' : IDL.Nat,
});
export const SheetCandidate = IDL.Record({
  'status' : IDL.Text,
  'weaknesses' : IDL.Opt(IDL.Text),
  'strengths' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'designation' : IDL.Text,
  'audioLink' : IDL.Opt(IDL.Text),
  'email' : IDL.Text,
  'score' : IDL.Opt(IDL.Nat),
  'department' : IDL.Text,
});

export const idlService = IDL.Service({
  'adminLogin' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'adminLogout' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'candidateLogin' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'completeInterview' : IDL.Func(
      [IDL.Text, EvaluationResult, IDL.Vec(IDL.Text)],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'createAdmin' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'createCandidate' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : Candidate, 'err' : IDL.Text })],
      [],
    ),
  'createInterviewSession' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : InterviewSession, 'err' : IDL.Text })],
      [],
    ),
  'getCandidateByEmail' : IDL.Func([IDL.Text], [IDL.Opt(Candidate)], []),
  'getCandidateByToken' : IDL.Func([IDL.Text], [IDL.Opt(Candidate)], []),
  'getCandidates' : IDL.Func([], [IDL.Vec(Candidate)], []),
  'getCandidatesForSync' : IDL.Func([], [IDL.Vec(Candidate)], []),
  'getDepartmentStats' : IDL.Func([], [IDL.Vec(DepartmentStat)], []),
  'getInterviewSession' : IDL.Func([IDL.Text], [IDL.Opt(InterviewSession)], []),
  'getStats' : IDL.Func([], [Stats], []),
  'syncFromSheets' : IDL.Func(
      [IDL.Vec(SheetCandidate)],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'updateTabSwitchCount' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'validateAdminSession' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'validateCandidateSession' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const EvaluationResult = IDL.Record({
    'weaknesses' : IDL.Text,
    'strengths' : IDL.Text,
    'confidenceRating' : IDL.Nat,
    'communicationRating' : IDL.Nat,
    'score' : IDL.Nat,
    'recommendation' : IDL.Text,
    'technicalRating' : IDL.Nat,
  });
  const Timestamp = IDL.Int;
  const Candidate = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'weaknesses' : IDL.Opt(IDL.Text),
    'strengths' : IDL.Opt(IDL.Text),
    'passcode' : IDL.Text,
    'name' : IDL.Text,
    'designation' : IDL.Text,
    'createdAt' : Timestamp,
    'audioLink' : IDL.Opt(IDL.Text),
    'email' : IDL.Text,
    'score' : IDL.Opt(IDL.Nat),
    'interviewDate' : IDL.Opt(Timestamp),
    'department' : IDL.Text,
  });
  const InterviewSession = IDL.Record({
    'status' : IDL.Text,
    'completedAt' : IDL.Opt(Timestamp),
    'startedAt' : Timestamp,
    'candidateEmail' : IDL.Text,
    'questions' : IDL.Vec(IDL.Text),
    'sessionId' : IDL.Text,
    'currentQuestionIndex' : IDL.Nat,
    'tabSwitchCount' : IDL.Nat,
  });
  const DepartmentStat = IDL.Record({
    'avgScore' : IDL.Nat,
    'count' : IDL.Nat,
    'department' : IDL.Text,
  });
  const Stats = IDL.Record({
    'avgScore' : IDL.Nat,
    'total' : IDL.Nat,
    'pending' : IDL.Nat,
    'completed' : IDL.Nat,
    'inProgress' : IDL.Nat,
  });
  const SheetCandidate = IDL.Record({
    'status' : IDL.Text,
    'weaknesses' : IDL.Opt(IDL.Text),
    'strengths' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'designation' : IDL.Text,
    'audioLink' : IDL.Opt(IDL.Text),
    'email' : IDL.Text,
    'score' : IDL.Opt(IDL.Nat),
    'department' : IDL.Text,
  });
  
  return IDL.Service({
    'adminLogin' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'adminLogout' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'candidateLogin' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'completeInterview' : IDL.Func(
        [IDL.Text, EvaluationResult, IDL.Vec(IDL.Text)],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'createAdmin' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'createCandidate' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : Candidate, 'err' : IDL.Text })],
        [],
      ),
    'createInterviewSession' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : InterviewSession, 'err' : IDL.Text })],
        [],
      ),
    'getCandidateByEmail' : IDL.Func([IDL.Text], [IDL.Opt(Candidate)], []),
    'getCandidateByToken' : IDL.Func([IDL.Text], [IDL.Opt(Candidate)], []),
    'getCandidates' : IDL.Func([], [IDL.Vec(Candidate)], []),
    'getCandidatesForSync' : IDL.Func([], [IDL.Vec(Candidate)], []),
    'getDepartmentStats' : IDL.Func([], [IDL.Vec(DepartmentStat)], []),
    'getInterviewSession' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(InterviewSession)],
        [],
      ),
    'getStats' : IDL.Func([], [Stats], []),
    'syncFromSheets' : IDL.Func(
        [IDL.Vec(SheetCandidate)],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'updateTabSwitchCount' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'validateAdminSession' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'validateCandidateSession' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], []),
  });
};

export const init = ({ IDL }) => { return []; };