/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Candidate {
  'id' : string,
  'status' : string,
  'weaknesses' : [] | [string],
  'strengths' : [] | [string],
  'passcode' : string,
  'name' : string,
  'designation' : string,
  'createdAt' : Timestamp,
  'audioLink' : [] | [string],
  'email' : string,
  'score' : [] | [bigint],
  'interviewDate' : [] | [Timestamp],
  'department' : string,
}
export interface DepartmentStat {
  'avgScore' : bigint,
  'count' : bigint,
  'department' : string,
}
export interface EvaluationResult {
  'weaknesses' : string,
  'strengths' : string,
  'confidenceRating' : bigint,
  'communicationRating' : bigint,
  'score' : bigint,
  'recommendation' : string,
  'technicalRating' : bigint,
}
export interface InterviewSession {
  'status' : string,
  'completedAt' : [] | [Timestamp],
  'startedAt' : Timestamp,
  'candidateEmail' : string,
  'questions' : Array<string>,
  'sessionId' : string,
  'currentQuestionIndex' : bigint,
  'tabSwitchCount' : bigint,
}
export interface SheetCandidate {
  'status' : string,
  'weaknesses' : [] | [string],
  'strengths' : [] | [string],
  'name' : string,
  'designation' : string,
  'audioLink' : [] | [string],
  'email' : string,
  'score' : [] | [bigint],
  'department' : string,
}
export interface Stats {
  'avgScore' : bigint,
  'total' : bigint,
  'pending' : bigint,
  'completed' : bigint,
  'inProgress' : bigint,
}
export type Timestamp = bigint;
export interface _SERVICE {
  'adminLogin' : ActorMethod<
    [string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'adminLogout' : ActorMethod<[string], boolean>,
  'candidateLogin' : ActorMethod<
    [string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'completeInterview' : ActorMethod<
    [string, EvaluationResult, Array<string>],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'createAdmin' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'createCandidate' : ActorMethod<
    [string, string, string, string],
    { 'ok' : Candidate } |
      { 'err' : string }
  >,
  'createInterviewSession' : ActorMethod<
    [string],
    { 'ok' : InterviewSession } |
      { 'err' : string }
  >,
  'getCandidateByEmail' : ActorMethod<[string], [] | [Candidate]>,
  'getCandidateByToken' : ActorMethod<[string], [] | [Candidate]>,
  'getCandidates' : ActorMethod<[], Array<Candidate>>,
  'getCandidatesForSync' : ActorMethod<[], Array<Candidate>>,
  'getDepartmentStats' : ActorMethod<[], Array<DepartmentStat>>,
  'getInterviewSession' : ActorMethod<[string], [] | [InterviewSession]>,
  'getStats' : ActorMethod<[], Stats>,
  'syncFromSheets' : ActorMethod<
    [Array<SheetCandidate>],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'updateTabSwitchCount' : ActorMethod<
    [string],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'validateAdminSession' : ActorMethod<[string], boolean>,
  'validateCandidateSession' : ActorMethod<[string], [] | [string]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];