/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface EvaluationResult {
    weaknesses: string;
    strengths: string;
    confidenceRating: bigint;
    communicationRating: bigint;
    score: bigint;
    recommendation: string;
    technicalRating: bigint;
}
export interface Candidate {
    id: string;
    status: string;
    weaknesses?: string;
    strengths?: string;
    passcode: string;
    name: string;
    designation: string;
    createdAt: Timestamp;
    audioLink?: string;
    email: string;
    score?: bigint;
    interviewDate?: Timestamp;
    department: string;
}
export type Timestamp = bigint;
export interface SheetCandidate {
    status: string;
    weaknesses?: string;
    strengths?: string;
    name: string;
    designation: string;
    audioLink?: string;
    email: string;
    score?: bigint;
    department: string;
}
export interface InterviewSession {
    status: string;
    completedAt?: Timestamp;
    startedAt: Timestamp;
    candidateEmail: string;
    questions: Array<string>;
    sessionId: string;
    currentQuestionIndex: bigint;
    tabSwitchCount: bigint;
}
export interface Stats {
    avgScore: bigint;
    total: bigint;
    pending: bigint;
    completed: bigint;
    inProgress: bigint;
}
export interface DepartmentStat {
    avgScore: bigint;
    count: bigint;
    department: string;
}
export interface backendInterface {
    adminLogin(email: string, password: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminLogout(token: string): Promise<boolean>;
    candidateLogin(email: string, passcode: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    completeInterview(sessionId: string, evaluation: EvaluationResult, audioLinks: Array<string>): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    createAdmin(email: string, password: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    createCandidate(email: string, name: string, department: string, designation: string): Promise<{
        __kind__: "ok";
        ok: Candidate;
    } | {
        __kind__: "err";
        err: string;
    }>;
    createInterviewSession(candidateEmail: string): Promise<{
        __kind__: "ok";
        ok: InterviewSession;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getCandidateByEmail(email: string): Promise<Candidate | null>;
    getCandidateByToken(token: string): Promise<Candidate | null>;
    getCandidates(): Promise<Array<Candidate>>;
    getCandidatesForSync(): Promise<Array<Candidate>>;
    getDepartmentStats(): Promise<Array<DepartmentStat>>;
    getInterviewSession(sessionId: string): Promise<InterviewSession | null>;
    getStats(): Promise<Stats>;
    syncFromSheets(sheetCandidates: Array<SheetCandidate>): Promise<{
        __kind__: "ok";
        ok: bigint;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateTabSwitchCount(sessionId: string): Promise<{
        __kind__: "ok";
        ok: bigint;
    } | {
        __kind__: "err";
        err: string;
    }>;
    validateAdminSession(token: string): Promise<boolean>;
    validateCandidateSession(token: string): Promise<string | null>;
}
import type { Candidate as _Candidate, InterviewSession as _InterviewSession, SheetCandidate as _SheetCandidate, Timestamp as _Timestamp } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async adminLogin(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminLogin(arg0, arg1);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminLogin(arg0, arg1);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminLogout(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminLogout(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminLogout(arg0);
            return result;
        }
    }
    async candidateLogin(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.candidateLogin(arg0, arg1);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.candidateLogin(arg0, arg1);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async completeInterview(arg0: string, arg1: EvaluationResult, arg2: Array<string>): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.completeInterview(arg0, arg1, arg2);
                return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeInterview(arg0, arg1, arg2);
            return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async createAdmin(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createAdmin(arg0, arg1);
                return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAdmin(arg0, arg1);
            return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async createCandidate(arg0: string, arg1: string, arg2: string, arg3: string): Promise<{
        __kind__: "ok";
        ok: Candidate;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createCandidate(arg0, arg1, arg2, arg3);
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCandidate(arg0, arg1, arg2, arg3);
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async createInterviewSession(arg0: string): Promise<{
        __kind__: "ok";
        ok: InterviewSession;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createInterviewSession(arg0);
                return from_candid_variant_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createInterviewSession(arg0);
            return from_candid_variant_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCandidateByEmail(arg0: string): Promise<Candidate | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCandidateByEmail(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCandidateByEmail(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCandidateByToken(arg0: string): Promise<Candidate | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCandidateByToken(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCandidateByToken(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCandidates(): Promise<Array<Candidate>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCandidates();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCandidates();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCandidatesForSync(): Promise<Array<Candidate>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCandidatesForSync();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCandidatesForSync();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDepartmentStats(): Promise<Array<DepartmentStat>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDepartmentStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDepartmentStats();
            return result;
        }
    }
    async getInterviewSession(arg0: string): Promise<InterviewSession | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getInterviewSession(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInterviewSession(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStats(): Promise<Stats> {
        if (this.processError) {
            try {
                const result = await this.actor.getStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStats();
            return result;
        }
    }
    async syncFromSheets(arg0: Array<SheetCandidate>): Promise<{
        __kind__: "ok";
        ok: bigint;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.syncFromSheets(to_candid_vec_n15(this._uploadFile, this._downloadFile, arg0));
                return from_candid_variant_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.syncFromSheets(to_candid_vec_n15(this._uploadFile, this._downloadFile, arg0));
            return from_candid_variant_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateTabSwitchCount(arg0: string): Promise<{
        __kind__: "ok";
        ok: bigint;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTabSwitchCount(arg0);
                return from_candid_variant_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTabSwitchCount(arg0);
            return from_candid_variant_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async validateAdminSession(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.validateAdminSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateAdminSession(arg0);
            return result;
        }
    }
    async validateCandidateSession(arg0: string): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.validateCandidateSession(arg0);
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateCandidateSession(arg0);
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Candidate_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Candidate): Candidate {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_InterviewSession_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InterviewSession): InterviewSession {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Candidate]): Candidate | null {
    return value.length === 0 ? null : from_candid_Candidate_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_InterviewSession]): InterviewSession | null {
    return value.length === 0 ? null : from_candid_InterviewSession_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: string;
    completedAt: [] | [_Timestamp];
    startedAt: _Timestamp;
    candidateEmail: string;
    questions: Array<string>;
    sessionId: string;
    currentQuestionIndex: bigint;
    tabSwitchCount: bigint;
}): {
    status: string;
    completedAt?: Timestamp;
    startedAt: Timestamp;
    candidateEmail: string;
    questions: Array<string>;
    sessionId: string;
    currentQuestionIndex: bigint;
    tabSwitchCount: bigint;
} {
    return {
        status: value.status,
        completedAt: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.completedAt)),
        startedAt: value.startedAt,
        candidateEmail: value.candidateEmail,
        questions: value.questions,
        sessionId: value.sessionId,
        currentQuestionIndex: value.currentQuestionIndex,
        tabSwitchCount: value.tabSwitchCount
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: string;
    weaknesses: [] | [string];
    strengths: [] | [string];
    passcode: string;
    name: string;
    designation: string;
    createdAt: _Timestamp;
    audioLink: [] | [string];
    email: string;
    score: [] | [bigint];
    interviewDate: [] | [_Timestamp];
    department: string;
}): {
    id: string;
    status: string;
    weaknesses?: string;
    strengths?: string;
    passcode: string;
    name: string;
    designation: string;
    createdAt: Timestamp;
    audioLink?: string;
    email: string;
    score?: bigint;
    interviewDate?: Timestamp;
    department: string;
} {
    return {
        id: value.id,
        status: value.status,
        weaknesses: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.weaknesses)),
        strengths: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.strengths)),
        passcode: value.passcode,
        name: value.name,
        designation: value.designation,
        createdAt: value.createdAt,
        audioLink: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.audioLink)),
        email: value.email,
        score: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.score)),
        interviewDate: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.interviewDate)),
        department: value.department
    };
}
function from_candid_variant_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: bigint;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Candidate;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Candidate;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Candidate_n4(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _InterviewSession;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: InterviewSession;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_InterviewSession_n10(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Candidate>): Array<Candidate> {
    return value.map((x)=>from_candid_Candidate_n4(_uploadFile, _downloadFile, x));
}
function to_candid_SheetCandidate_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SheetCandidate): _SheetCandidate {
    return to_candid_record_n17(_uploadFile, _downloadFile, value);
}
function to_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: string;
    weaknesses?: string;
    strengths?: string;
    name: string;
    designation: string;
    audioLink?: string;
    email: string;
    score?: bigint;
    department: string;
}): {
    status: string;
    weaknesses: [] | [string];
    strengths: [] | [string];
    name: string;
    designation: string;
    audioLink: [] | [string];
    email: string;
    score: [] | [bigint];
    department: string;
} {
    return {
        status: value.status,
        weaknesses: value.weaknesses ? candid_some(value.weaknesses) : candid_none(),
        strengths: value.strengths ? candid_some(value.strengths) : candid_none(),
        name: value.name,
        designation: value.designation,
        audioLink: value.audioLink ? candid_some(value.audioLink) : candid_none(),
        email: value.email,
        score: value.score ? candid_some(value.score) : candid_none(),
        department: value.department
    };
}
function to_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<SheetCandidate>): Array<_SheetCandidate> {
    return value.map((x)=>to_candid_SheetCandidate_n16(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
